version: '3'
services:
    php:
        build: ./api/docker
        volumes:
            - ./api:/var/www/html:delegated
        ports:
            - 8000:80
        environment:
            HTTPD__DocumentRoot: '/var/www/html/'
            HTTPD__ServerAdmin: 'ales.jandera@gmail.com'
            HTTPD_a2enmod:  'rewrite status expires'
    mongo:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 3FSFSDFDFrew
            MONGO_INITDB_DATABASE: arualcms
        ports:
            - "27017:27017"
        volumes:
            - ./data:/data/db
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
