version: '3'
services:
    arual-api:
        build: .
        entrypoint: [ "sh", "/entrypoint.sh" ]
        environment:
            - HOST=arual-data
            - USER=demo
            - PASSWORD=demo
            - DATABASE=arual
            - PORT=5432
        volumes:
            - "../../api:/application"
        ports:
            - "9009:8888"

    arual-data:
        image: postgres:13
        environment:
            - POSTGRES_PASSWORD=demo
            - POSTGRES_USER=demo
            - POSTGRES_DB=arual
            - POSTGRES_EXTENSIONS=uuid-ossp
        volumes:
            - "data:/var/lib/postgresql/data"

    arual-adminer:
        image: adminer
        restart: always
        ports:
            - 5051:8080

volumes:
    data:
