version: '3'
services:
    php:
        build: .
        ports:
            - 8000:80
        volumes:
            -   ./../../api:/var/www/html
        environment:
            mongo_dsn: 'mongodb://root:3FSFSDFDFrew@mongo:27017'
            mongo_dbname: 'arualcms'
    mongo:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 3FSFSDFDFrew
            MONGO_INITDB_DATABASE: arualcms
        ports:
            - "27017:27017"
        volumes:
            - ./data:/data/db
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
