version: '3'
services:
    arual-api:
        build: .
        entrypoint: [ "sh", "/entrypoint.sh" ]
        environment:
            - HOST=arual-data
            - USER=demo
            - PASSWORD=demo
            - DATABASE=arual
            - PORT=5432
            - SMTP_HOST=in-v3.mailjet.com
            - SMTP_PORT=587
            - SMTP_FROM=info@arualcms.eu
            - SMTP_USER=1effbfb5b0b27aa6082fa82a830061db
            - SMTP_PW=9007a316cdae207cccda97edaabc5ca4
            - DEEPL=5d240297-dd28-e8bd-91f8-a72acfd8b9be:fx
        volumes:
            - "../../api:/application"
        ports:
            - "9009:8888"

    arual-data:
        image: postgres:13
        environment:
            - POSTGRES_PASSWORD=demo
            - POSTGRES_USER=demo
            - POSTGRES_DB=arual
            - POSTGRES_EXTENSIONS=uuid-ossp
        volumes:
            - "data:/var/lib/postgresql/data"

    arual-adminer:
        image: adminer
        restart: always
        ports:
            - 5051:8080

volumes:
    data:
