version: '3'
services:
    php:
        container_name: arualcms_production
        build: ./docker
        volumes:
            - .:/var/www/html:delegated
        ports:
            - 8001:80
        environment:
            HTTPD__DocumentRoot: '/var/www/html/'
            HTTPD__ServerAdmin: 'ales.jandera@gmail.com'
            HTTPD_a2enmod:  'rewrite status expires'
